MYCE_DATA = {
    "basic": {
        "cost": 200,
        "damage": 5,
        "cooldown": 1500,
        "spacing": 325,
        "aoe_radius": 0,
        "sheet_path": "assets/images/myce/sheets/myce1_shooting_spritesheet.png",
        "icon_path": "assets/images/myce/sprites/myce1.png",
        "label": "Basic Myce",
        "tooltip": "Cost:200||Balanced single-target tower.",
    },
    "lumber": {
        "cost": 275,
        "damage": 7,
        "cooldown": 900,
        "spacing": 320,
        "aoe_radius": 0,
        "sheet_path": "assets/images/myce/sheets/lumbermyce_shooting.png",
        "icon_path": "assets/images/myce/sprites/map_builder_myce.png",
        "label": "Lumber Myce",
        "tooltip": "Cost:275||Faster attacks and higher damage.",
    },
    "money": {
        "cost": 300,
        "damage": 5,
        "cooldown": 1500,
        "spacing": 316,
        "aoe_radius": 0,
        "sheet_path": "assets/images/myce/sheets/money_mice_shooting.png",
        "icon_path": "assets/images/myce/sprites/map_money_myce.png",
        "label": "Money Myce",
        "tooltip": "Cost:300||Economy tower with basic damage.",
    },
    "pumpkin": {
        "cost": 350,
        "damage": 8,
        "cooldown": 1600,
        "spacing": 316,
        "aoe_radius": 90,
        "sheet_path": "assets/images/myce/sheets/pumpkyce_shooting.png",
        "icon_path": "assets/images/myce/sprites/map_pumpkin_myce.png",
        "label": "Pumpkyce",
        "tooltip": "Cost:350||Area damage around the target.",
    },
}